spring:
  datasource:
    url: jdbc:mysql://db:3306/contabildb
    username: root
    password: 3012
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Configurações adicionais, se necessário
server:
  port: 8080

# Configurações de log, se necessário
logging:
  level:
    root: INFO
    org.springframework: DEBUG

